---
# yaml-language-server: $schema=https://raw.githubusercontent.com/marcolongol/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: restic-config-mailserver
  namespace: mail-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: restic-config-mailserver
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_PASSWORD: |-
          {{ .RESTIC_PASSWORD }}
        RESTIC_REPOSITORY: |-
          {{ .RESTIC_REPOSITORY }}/docker-mailserver/mail-data
        AWS_ACCESS_KEY_ID: |-
          {{ .AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: |-
          {{ .AWS_SECRET_ACCESS_KEY }}
  dataFrom:
    - extract:
        key: RESTIC
