---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ./replicationsource.yaml
configMapGenerator:
  - name: screeps-config
    namespace: screeps-system
    files:
      - ./config/config.yaml
      - ./config/market.yaml
    options:
      disableNameSuffixHash: true
