apiVersion: v1
kind: Secret
metadata:
    name: screeps-env
    namespace: screeps-system
stringData:
    STEAM_KEY: ENC[AES256_GCM,data:Sn/oxCahRU4P5gYC+7qNH+8K7w4z+gBzUZsQrlktp9k=,iv:r4ILX/fXKiJnJmOAN+wPw8DrDs552dcdoOnTO5lHkK0=,tag:s9ZgrmYYE63d8o/zcVTz+A==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5d3hKVVZUcGsxVHRwbG1M
            ckFNWTNmYSt4TmY1RW1ldkJQWWRVMGxwOWswCkUyZzg1YXJuNkZGbEV5M1l1ei9T
            OUt0UzlMWlpHVkdTSnM4ekhYRW1ZODgKLS0tIHRLQkhYeEVJSVB4ZTVIa0RweUYw
            c3NMWVVML3RiMHF6empQRFRVMm90U1EKKg9+rLDSCpVhAikUBX52pl6+JLrA0ue0
            NqYeN7ae4s76tYw0VxoV7Du3wmJULHBo0ZBZ7gac8ZDWlFSYzZkz3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-11T18:49:45Z"
    mac: ENC[AES256_GCM,data:sEw1JUvCBM5RMbRVHMlza97rbPptBmWhDpWuVnSI9NXfGTtv/lm+DGRzkZv0JuVFqiRd+28Sl63+mS435+x9TFHrddBfMBkVWJFx96TznMpYndBa3nCiWEfP8mko9Gcnwsstxv2eeNKq0CZygAKSJaETmvwKcE02BCiwOh5cgRU=,iv:f4sgPsHLi98Y8en+UvOhGG18DihDV39QocPgmG6J/U0=,tag:xYuM3z79Hn6SxABs148lMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.8.1
