---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app metrics-server
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: monitoring-system
  releaseName: *app
  chart:
    spec:
      chart: *app
      version: 3.12.2
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      interval: 10m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    replicas: 2
