---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app reflector
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: kube-system
  releaseName: *app
  chart:
    spec:
      chart: *app
      version: 7.1.288
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
