# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unleash-proxy-prod
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: unleash-system
  releaseName: *app
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      hostname: "unleash-proxy.${SECRET_DOMAIN_0}"
    controllers:
      unleash-proxy:
        containers:
          main:
            image:
              repository: unleashorg/unleash-proxy
              tag: "v1.4.8"
            resources:
              requests:
                cpu: 15m
                memory: 164Mi
              limits:
                memory: 175Mi
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            env:
              UNLEASH_URL: "http://unleash-api.unleash-system.svc.cluster.local:4242/api"
              UNLEASH_PROXY_CLIENT_KEYS:
                valueFrom:
                  secretKeyRef:
                    name: unleash-secret
                    key: UNLEASH_PROXY_CLIENT_KEY
              UNLEASH_API_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: unleash-secret
                    key: UNLEASH_PROD_API_CLIENT_TOKEN
    service:
      main:
        controller: unleash-proxy
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: &host unleash-proxy.${SECRET_DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: ${SECRET_DOMAIN_0}-prod
