---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flux-manifests
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/fluxcd/flux-manifests
  ref:
    tag: v2.3.0

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-manifests
  namespace: flux-system
spec:
  path: ./
  sourceRef:
    kind: OCIRepository
    name: flux-manifests
  interval: 30m
  prune: true
  wait: true
