---
# yaml-language-server: https://raw.githubusercontent.com/marcolongol/CRDs-catalog/refs/heads/main/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
  namespace: secrets-system
spec:
  provider:
    onepassword:
      connectHost: https://onepassword-connect.${SECRET_DOMAIN_0}
      vaults:
        secrets: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: op-credentials
            key: token
            namespace: secrets-system
