---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pgo
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: postgres-operator
  releaseName: *app
  chart:
    spec:
      chart: pgo
      version: 5.7.1
      sourceRef:
        kind: HelmRepository
        name: crunchydata-charts
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
