---
# yaml-language-server: $schema=https://raw.githubusercontent.com/marcolongol/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unleash-secret
  namespace: unleash-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unleash-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        UNLEASH_DEFAULT_ADMIN_USERNAME: |-
          {{ .UNLEASH_DEFAULT_ADMIN_USERNAME }}
        UNLEASH_DEFAULT_ADMIN_PASSWORD: |-
          {{ .UNLEASH_DEFAULT_ADMIN_PASSWORD }}
  dataFrom:
    - extract:
        key: UNLEASH
