# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unleash-api
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: unleash-system
  releaseName: *app
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      hostname: "unleash.${SECRET_DOMAIN_0}"
    controllers:
      unleash:
        containers:
          main:
            image:
              repository: unleashorg/unleash-server
              tag: 6.3.0
            resources:
              requests:
                cpu: 15m
                memory: 164Mi
              limits:
                memory: 175Mi
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            env:
              DATABASE_HOST:
                valueFrom:
                  secretKeyRef:
                    name: pgo-cluster-pguser-unleash
                    key: host
              DATABASE_NAME:
                valueFrom:
                  secretKeyRef:
                    name: pgo-cluster-pguser-unleash
                    key: dbname
              DATABASE_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: pgo-cluster-pguser-unleash
                    key: user
              DATABASE_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: pgo-cluster-pguser-unleash
                    key: password
              UNLEASH_DEFAULT_ADMIN_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: unleash-secret
                    key: UNLEASH_DEFAULT_ADMIN_USERNAME
              UNLEASH_DEFAULT_ADMIN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: unleash-secret
                    key: UNLEASH_DEFAULT_ADMIN_PASSWORD
    service:
      main:
        controller: unleash
        ports:
          http:
            port: 4242
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: ${CONFIG_NGINX_WHITELIST}
        hosts:
          - host: &host unleash.${SECRET_DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: ${SECRET_DOMAIN_0}-prod
