---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &certName ${SECRET_DOMAIN_0}-prod
  namespace: networking-system
spec:
  secretName: *certName
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ".*"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "^(?!networking-system$).*$"
  issuerRef:
    name: ${SECRET_DOMAIN_0}-prod
    kind: ClusterIssuer
  dnsNames:
    - ${SECRET_DOMAIN_0}
    - "*.${SECRET_DOMAIN_0}"

---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &certName ${SECRET_DOMAIN_0}-staging
  namespace: networking-system
spec:
  secretName: *certName
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ".*"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "^(?!networking-system$).*$"
  issuerRef:
    name: ${SECRET_DOMAIN_0}-staging
    kind: ClusterIssuer
  dnsNames:
    - ${SECRET_DOMAIN_0}
    - "*.${SECRET_DOMAIN_0}"

---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &certName ${SECRET_DOMAIN_1}-prod
  namespace: networking-system
spec:
  secretName: *certName
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ".*"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "^(?!networking-system$).*$"
  issuerRef:
    name: ${SECRET_DOMAIN_1}-prod
    kind: ClusterIssuer
  dnsNames:
    - ${SECRET_DOMAIN_1}
    - "*.${SECRET_DOMAIN_1}"

---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &certName ${SECRET_DOMAIN_1}-staging
  namespace: networking-system
spec:
  secretName: *certName
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ".*"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "^(?!networking-system$).*$"
  issuerRef:
    name: ${SECRET_DOMAIN_1}-staging
    kind: ClusterIssuer
  dnsNames:
    - ${SECRET_DOMAIN_1}
    - "*.${SECRET_DOMAIN_1}"

---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &certName ${SECRET_DOMAIN_0}-selfsigned
  namespace: networking-system
spec:
  secretName: *certName
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ".*"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "^(?!networking-system$).*$"
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - ${SECRET_DOMAIN_0}

---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &certName ${SECRET_DOMAIN_1}-selfsigned
  namespace: networking-system
spec:
  secretName: *certName
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ".*"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "^(?!networking-system$).*$"
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - ${SECRET_DOMAIN_1}
