---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft
  namespace: flux-system
spec:
  interval: 10m
  releaseName: *app
  targetNamespace: minecraft-system
  chart:
    spec:
      chart: minecraft
      version: 4.23.7
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 15m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      hostname: "minecraft.${SECRET_DOMAIN_0}"
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: 2025.2.1-java21
    resources:
      requests:
        cpu: 4000m
        memory: 12288Mi
    persistence:
      dataDir:
        enabled: true
        Size: 50Gi
    envFrom:
      - secretRef:
          name: minecraft-secret
      - configMapRef:
          name: minecraft-config
    minecraftServer:
      eula: true
      version: 1.21.1
      type: AUTO_CURSEFORGE
      forceReDownload: true
      jvmXXOpts: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1"
      rcon:
        enabled: true
        serviceType: ClusterIP
        existingSecret: minecraft-secret
        secretKey: RCON_PASSWORD
      autoCurseForge:
        apiKey:
          existingSecret: minecraft-secret
          secretKey: CF_API_KEY
        slug: all-the-mods-10
        excludeMods:
          - sodium
          - sodium-extra
          - reeses-sodium-options
      memory: 12000M
      difficulty: hard
      spawnProtection: 0
      maxTickTime: -1
      gameMode: survival
      pvp: true
      onlineMode: true
      ops: "chaosface_"
      worldSaveName: KubeMine
      viewDistance: 12
      serviceType: ClusterIP
