---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gha-runner-scale-set-controller
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: arc-system
  releaseName: *app
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
