---
# yaml-language-server: $schema=https://raw.githubusercontent.com/marcolongol/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smbcreds
  namespace: storage-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: smbcreds
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: |-
          {{ .SMB_KUBERNETES_USERNAME }}
        password: |-
          {{ .SMB_KUBERNETES_PASSWORD }}
  dataFrom:
    - extract:
        key: SMB
