apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox
  namespace: networking-system
subsets:
  - addresses:
      - ip: ${CONFIG_PROXMOX_IP_ADDRESS}
    ports:
      - name: https
        port: 8006
        protocol: TCP
