apiVersion: v1
kind: Endpoints
metadata:
  name: registry
  namespace: networking-system
subsets:
  - addresses:
      - ip: ${CONFIG_DOCKER_SERVER_IP_ADDRESS}
    ports:
      - name: https
        port: 443
        protocol: TCP
