---
# yaml-language-server: $schema=https://raw.githubusercontent.com/marcolongol/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-secret
  namespace: auth-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authelia-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OIDC_JWKS_KEY: |-
          {{ .OIDC_JWKS_KEY }}
        AUTHELIA_DUO_API_HOSTNAME: |-
          {{ .AUTHELIA_DUO_API_HOSTNAME }}
        AUTHELIA_DUO_API_INTEGRATION_KEY: |-
          {{ .AUTHELIA_DUO_API_INTEGRATION_KEY }}
        AUTHELIA_DUO_API_SECRET_KEY: |-
          {{ .AUTHELIA_DUO_API_SECRET_KEY }}
        AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: |-
          {{ .AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET }}
        AUTHELIA_STORAGE_ENCRYPTION_KEY: |-
          {{ .AUTHELIA_STORAGE_ENCRYPTION_KEY }}
        MINIO_OAUTH_CLIENT_ID: |-
          {{ .MINIO_OAUTH_CLIENT_ID }}
        MINIO_OAUTH_CLIENT_HASHED_SECRET: |-
          {{ .MINIO_OAUTH_CLIENT_HASHED_SECRET }}
        KUBERNETES_OIDC_CLIENT_ID: |-
          {{ .KUBERNETES_OIDC_CLIENT_ID }}
        KUBERNETES_OIDC_CLIENT_HASHED_SECRET: |-
          {{ .KUBERNETES_OIDC_CLIENT_HASHED_SECRET }}
        AWX_OIDC_CLIENT_ID: |-
          {{ .AWX_OIDC_CLIENT_ID }}
        AWX_OIDC_CLIENT_HASHED_SECRET: |-
          {{ .AWX_OIDC_CLIENT_HASHED_SECRET }}
        OAUTH2_PROXY_OIDC_CLIENT_ID: |-
          {{ .OAUTH2_PROXY_OIDC_CLIENT_ID }}
        OAUTH2_PROXY_OIDC_CLIENT_HASHED_SECRET: |-
          {{ .OAUTH2_PROXY_OIDC_CLIENT_HASHED_SECRET }}
  dataFrom:
    - extract:
        key: AUTHELIA
    - extract:
        key: MINIO
    - extract:
        key: KUBERNETES
    - extract:
        key: AWX
    - extract:
        key: OAUTH2_PROXY
