---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authelia
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: auth-system
  releaseName: authelia
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      authelia:
        replicas: 1
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: ghcr.io/authelia/authelia
              tag: 4.38.8
            resources:
              requests:
                cpu: 1m
                memory: 50Mi
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            envFrom:
              - secretRef:
                  name: authelia-secret
            env:
              X_AUTHELIA_CONFIG: /config/configuration.yaml
              X_AUTHELIA_CONFIG_FILTERS: template
              AUTHELIA_STORAGE_POSTGRES_ADDRESS: tcp://pgo-cluster-ha.postgres-operator.svc.cluster.local:5432
              AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER:
                valueFrom:
                  secretKeyRef:
                    name: lldap-secret
                    key: LDAP_BIND_DN
              AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: lldap-secret
                    key: LLDAP_LDAP_USER_PASS
              AUTHELIA_NOTIFIER_SMTP_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: lldap-secret
                    key: LLDAP_LDAP_USER_PASS
              AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN:
                valueFrom:
                  secretKeyRef:
                    name: lldap-secret
                    key: LLDAP_LDAP_BASE_DN
              AUTHELIA_STORAGE_POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: pgo-cluster-pguser-authelia
                    key: password
              AUTHELIA_STORAGE_POSTGRES_DATABASE:
                valueFrom:
                  secretKeyRef:
                    name: pgo-cluster-pguser-authelia
                    key: dbname
              AUTHELIA_STORAGE_POSTGRES_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: pgo-cluster-pguser-authelia
                    key: user
    service:
      main:
        controller: authelia
        ports:
          http:
            port: 9091
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            add_header Cache-Control "no-store";
            add_header Pragma "no-cache";
        hosts:
          - host: &host auth.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: ingress-nginx-tls
    persistence:
      config:
        enabled: true
        type: configMap
        name: authelia-config
        globalMounts:
          - path: /config
            readOnly: true
      secret-files:
        enabled: true
        type: secret
        name: authelia-secret-files
        globalMounts:
          - path: /config/secret
