---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${SECRET_DOMAIN_0}-prod
spec:
  acme:
    email: ${SECRET_CLUSTER_EMAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: ${SECRET_PUBLIC_EMAIL}
            apiTokenSecretRef:
              name: cloudflare-api-key
              key: api-key
        selector:
          dnsZones:
            - ${SECRET_DOMAIN_0}

---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${SECRET_DOMAIN_0}-staging
spec:
  acme:
    email: ${SECRET_CLUSTER_EMAIL}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: ${SECRET_PUBLIC_EMAIL}
            apiTokenSecretRef:
              name: cloudflare-api-key
              key: api-key
        selector:
          dnsZones:
            - ${SECRET_DOMAIN_0}

---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${SECRET_DOMAIN_1}-prod
spec:
  acme:
    email: ${SECRET_CLUSTER_EMAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: ${SECRET_PUBLIC_EMAIL}
            apiTokenSecretRef:
              name: cloudflare-api-key
              key: api-key
        selector:
          dnsZones:
            - ${SECRET_DOMAIN_1}

---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${SECRET_DOMAIN_1}-staging
spec:
  acme:
    email: ${SECRET_CLUSTER_EMAIL}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: ${SECRET_PUBLIC_EMAIL}
            apiTokenSecretRef:
              name: cloudflare-api-key
              key: api-key
        selector:
          dnsZones:
            - ${SECRET_DOMAIN_1}

---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
