---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app godaddy-webhook
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: networking-system
  releaseName: *app
  chart:
    spec:
      chart: *app
      version: v0.3.0
      sourceRef:
        kind: HelmRepository
        name: godaddy-webhook
        namespace: flux-system
      interval: 10m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    groupName: acme.${SECRET_DOMAIN}
