---
# yaml-language-server: $schema=https://raw.githubusercontent.com/marcolongol/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller-auth-secret
  namespace: arc-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: actions-runner-controller-auth-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        github_app_id: |-
          {{ .GITHUB_APP_ID }}
        github_app_installation_id: |-
          {{ .GITHUB_APP_INSTALLATION_ID_ORG }}
        github_app_private_key: |-
          {{ .GITHUB_APP_PRIVATE_KEY }}
  dataFrom:
    - extract:
        key: GITHUB
