---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gha-runner-scale-set
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: arc-system
  releaseName: *app
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.10.1
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    containerMode:
      type: dind
    githubConfigSecret: actions-runner-controller-auth-secret
    githubConfigUrl: https://github.com/marcolongo-cloud
    maxRunners: 6
    minRunners: 1
    runnerScaleSetName: arc-runner-set
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/onedr0p/actions-runner:2.321.0@sha256:a7539dc157f3f0129f49459826576ab53a529580916bb8a09a395e61e38354c0
            command: ["/home/runner/run.sh"]
