---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: lldap
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: auth-system
  releaseName: lldap
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      lldap:
        containers:
          main:
            image:
              repository: ghcr.io/lldap/lldap
              tag: v0.5.0
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            envFrom:
              - secretRef:
                  name: lldap-secret
            env:
              - name: LLDAP_LDAP_PORT
                value: &ldapPort 3890
              - name: LLDAP_HTTPS_PORT
                value: &web 17170
    service:
      main:
        controller: lldap
        ports:
          ldap:
            enabled: true
            protocol: TCP
            port: *ldapPort
          web:
            enabled: true
            protocol: TCP
            port: *web
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8
        hosts:
          - host: &host ldap.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: web
        tls:
          - hosts:
              - *host
            secretName: ingress-nginx-tls
    persistence:
      data:
        enabled: true
        existingClaim: lldap-data
        globalMounts:
          - path: /data
