---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lldap
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: auth-system
  releaseName: lldap
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      lldap:
        containers:
          main:
            image:
              repository: ghcr.io/lldap/lldap
              tag: v0.5.0
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            env:
              LLDAP_VERBOSE: "true"
              LLDAP_HTTP_URL: "https://ldap.${SECRET_DOMAIN_0}"
              LLDAP_LDAP_USER_EMAIL: admin@${SECRET_DOMAIN_0}
              LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: "true"
              LLDAP_SMTP_OPTIONS__SERVER: mail.${SECRET_DOMAIN_0}
              LLDAP_SMTP_OPTIONS__PORT: 587
              LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION: STARTTLS
              LLDAP_SMTP_OPTIONS__USER: admin@${SECRET_DOMAIN_0}
              LLDAP_SMTP_OPTIONS__FROM: "LDAP Admin <admin@${SECRET_DOMAIN_0}>"
              LLDAP_SMTP_OPTIONS__REPLY_TO: "Do Not Reply <noreply@${SECRET_DOMAIN_0}>"
            envFrom:
              - secretRef:
                  name: lldap-secret
    service:
      main:
        controller: lldap
        ports:
          ldap:
            enabled: true
            protocol: TCP
            port: 389
            targetPort: 3890
          web:
            enabled: true
            protocol: TCP
            port: 17170
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: ${CONFIG_NGINX_WHITELIST}
        hosts:
          - host: &host ldap.${SECRET_DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: web
        tls:
          - hosts:
              - *host
            secretName: ingress-nginx-prod
    persistence:
      data:
        enabled: true
        existingClaim: lldap-data
        globalMounts:
          - path: /data
