apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-data
  namespace: auth-system
  labels:
    app.kubernetes.io/name: lldap
spec:
  storageClassName: mayastor-nvmf
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
