apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
    namespace: auth-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: auth-system,mail-system,networking-system
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ^(?!auth-system$).*$
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:ds0BCNLRtCjskGMjnVQ07tOcLoqPluFsrzwTAp+v5v9OTxtuy0Ke4a8yosmgGM9VYZd64er5EeTvu+LAi2w4wdlaBC1w0gM477Swv/6j3Z1Ux7Tpv6zvL1nJ/rNRb5NA9QoYalmzQxMJHAHSRKx2ly3Tf0Q8bVFi0xibnyh/aIXqsLWuWwXwxgBfTqKkxxjEz8oB2uh11FmljrLZEaDc/4w/7tOgbCVyUJaxXzA1PZK0Z7bF3UPF486XCXO7ZOqoWKnRSJY7DXFuJ3t8lEUPbglg0P7N5hvYVg0knivpIOmMinKJ92AemcRlKPaOlLjvU2Jx3OXWCkjLo2wSkZgXvCLUgC/l95yhHs0vhbgumcZXbyW6Cd2YTHu9nA7xwlSJo26GoWP4rI/L8RtGyN8sMpRwUCUt2R0JGnp1PrrSr7sFdweIzhDXakT1L2sAwkb2CfAtWvSHH7M=,iv:cIT/kj/bJ5zJ9Vjm8EEtyFjwvOWXJJt8vQuvrBcTV1w=,tag:s2xqgPw+hoA2Zirc3CpYkg==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:Q/6FXk5KVCSHAPQ=,iv:I79IKtDcKRPacAOBISgtXQLkPGSCnExfddDRKav7wBo=,tag:C1V69+E7vbRgpFhBREkglg==,type:str]
    LLDAP_LDAP_BASE_DN: ENC[AES256_GCM,data:IzfMcfk2Ljm9DgjSthgDtKuGLZXPhg==,iv:9mvZXjPFOW5GAY2jyyh05XUpyWYgaAp6UjzK7xSEvho=,tag:caBrJy7I5I5zsVS6KpQDNg==,type:str]
    LDAP_BIND_DN: ENC[AES256_GCM,data:S43R7kvf6LeETbFVD2WpMc0wseI2GUCZpfcXO0/1vcDbgCF8jxJdKHGm,iv:h6Y2vAfO2owfoJ0c55zOUgUqXZlnJW9MpTcH+C0iC7g=,tag:T547o7MJeBNaZyGGYd3b2Q==,type:str]
    LDAP_SEARCH_BASE: ENC[AES256_GCM,data:QhZqI11XIcSDGt/612s+eTRcxDtWM07FFmgPbAzthLQ=,iv:iPx2oDxfE9l2NKdS/OoXBMJ46q3nBeMfIZkMU1Mp3L0=,tag:3NCSxHexS+lkOBGcbK69Ow==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaFRyVit3NmJHWDBNYy9Y
            WC9UdW0vamszT01JdUtPcGRLUU5jTHN1cmlvClJxc0pMVU1SSVNPK0x1ZXpOcVht
            QUtxSWE1TVltNjA1WVRWT0llMXhhRjAKLS0tIFZSUHN0UkVlS0tjbjN0dzMvVHM4
            Y3dxOUc2TUgzc3RwM0pISlYzaHZBOGsKy05R2MYkEdwL3HctalVQ3miWU999QnkB
            0pgsLbiaL63bokO18Eq6AgF5Jw/wNoRoKLO31Cnndnm2rDD5gY0gKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-05T02:34:05Z"
    mac: ENC[AES256_GCM,data:+bHGLrD1acyKBusD94NhCvkA4stJBSk6takW/TnD95hm+WcYhrFJeYFy85TCBD/YPXSXGfNW7VowbVWFce3TOh6bSEG8TMfjbr8kbgzd08Vu56XP9Iv8AF8wG+AIdKppY8OA/AOqGQSJ8cx4ZIlHEwWgUcUxxilE9QuMntQxXLc=,iv:fijuwqaPNaaWcZ7nKiw6O4jM5aaE+ARRtFdLAnZIZyk=,tag:sHq7z96XVA7ZelnlJuIYwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.8.1
