apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
    namespace: auth-system
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:vq8DvY7ZDaXDZIymP/EIl1Ag/Ovlgb3hePY6eX4jxrIQ+xT51+qXUjuwSFgcrl7QmeLJtgaWK8n2u3PdlN2e0tEvF/BNnzE0ARE+K3oBKbMFNkVVwmG4lmA2QuR+3vYRb25gpWUNdrX/C1/2MysCWVhNVVpX/JXpxtsEbkC7crnvgz8OBOHm9k/c06TN1ngwQnl7X6R/g3m+QnmqDVdldpcBcFn9Jt3C4J6kSdu9LIhQc030n5yxjQHqabhABML73/4UIuQBew8Z96QnkFD1RrKXhwPpkABfdTOR3w2cBs97BpB6ZfSmBAU/uq40UBid5pX/DCAhOD7dg3VtCFJs5CHRYZWMqA59MJ1xhXIrjx/sxiq9+UH7UlhtNKhetCptDcP0EUE56GXz2owO8sQ2vASMi7c4suAapwLDb72fWF5OmxFC6an7u2lHuArbQdn+IsZXenAVu/4=,iv:+j6trNunPcSd6HqCbTezYj16VgSCy7oXN62l7C7FDog=,tag:biLCRei2uFh9TOPJxYH0Ug==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:I4Xmnj6Fs4vBAZs=,iv:O9WwVQK20O6bqAsZybILbjDNg96xwqcvMF6B00GROjU=,tag:5qw0uGkbjFeVb6oZPNmvWA==,type:str]
    LLDAP_LDAP_BASE_DN: ENC[AES256_GCM,data:l4uY/Gxvfx7Hd4TCCI8NpDYjt8SbWQ==,iv:BL78eOns6ZJNVyCFQHztND7KUw0nXsa2BzK9F97ZTY8=,tag:Ml68N4G1FEnlwwiLVPw9sA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVc3NPQXNmZ0dhanduVWNC
            aW5FYXZ4SWNEOTlUU2JhWVFOWEpyVjV5YldnCkYvRnE1bnZteHl4d1ZqV1c2K2Rh
            ejI4aWFYSytiWUQ0cmE3TWh2cmF0Q1EKLS0tIElzZVVGWjdWaTc4TFJvNzBKRS9s
            VUxpSHZ1OWpNb1ozaXI1SzNTWllSRncKGJXEfIG5s6Qu/JEMeWmLoIckybCsWtOa
            WF9KRHOB06VNe4KKGNCVZa3H/gZMlfKEeDEVkb1rdDl373I9jBSU9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-30T06:18:43Z"
    mac: ENC[AES256_GCM,data:TueYwhVh4PauT7nPxmOCGJ0WkfWxyJ4tgrttFh7K7hXTWcq64xyEltbDX0E/Q1Xk8gCCxPE2JHD1gmP1hqFBZi7TNVmsHnM758CnOIGkSrrDM1c1EB6ArZXTiPjrTnibRzuAofHQqmTqNSrV1CZnvrgKi5r1/OxMQdprX9zQH5g=,iv:/ziJy3mFYWwi281abCFodFXhS5OEF1f2BZ5qKc6Q3To=,tag:dsmGXfy8MWQdlFkOkJeLaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.8.1
