apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
    namespace: auth-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: auth-system,mail-system,networking-system
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ^(?!auth-system$).*$
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:ziWGGvEUEybVJJR8PwjrxjLVWWPv2HL3zEg3sd4TrhMD1dXi3Wn2OdDJWbvEAqKc+gRLuQywz7XZ4k1dWhYyksXLW1bnN4h9k9ZCSU5xA7209RDvwBCJ3x8Q4JOOrS4o4gA40ZpamkGskF5tMyl/PCIeoegb7OhZUIm/5lg0IUoL03MoxmEO7kV+Ggi02cu8ybFbVptId1Rp7Iri44/P3n/5PEK0KXsMAJYC8K0Su1wuWBNhiCoHV+g7zg9sd5UF2wGrctSBVma5hzKSHxCwqg+03nkOirLLXIfMlV6JWvzgTT+5gnwFxAr82oZiGXQpslVHUN+BuRHFqaDltU47b0LFaf/48zeVg9WzAmd0np4Gr43cZ6XNfBkwa4Nhkl8icW0tNnm2MqmBMBzP0W6CL825WaovEsZti0Z9dPQio7DYl8Gp4vOMPuAoHmlDiZ63d0y7xKsAleE=,iv:7p8WeqhgAlynk8UM9am+SoMQP2V2iSean8/SnSS/iBI=,tag:DB3r3a/w1r6dQKZCc7u9eQ==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:0X3MNNlJHB2P4S4=,iv:2Vgyg29qKLD9PUbFlSUR+hy5JbFzMIYRnPR8WYTOK2E=,tag:VXjj2ioOO1O/18/c4E/j1A==,type:str]
    LLDAP_SMTP_OPTIONS__PASSWORD: ENC[AES256_GCM,data:hUw5ZlwYXDsOGyg=,iv:Pbp86G/jUcW3CZx5S4FNV7ybb0uAv+45Z5Kc2HfAoPs=,tag:38EKwFLKC7aq4j7UkoRRUw==,type:str]
    LLDAP_LDAP_BASE_DN: ENC[AES256_GCM,data:pkww4FCwHfDo7cpRwIez4VFD8xpW2Q==,iv:WbaAGSdB0abG6oq6+ui1C+vxtbTPRVzc/8mUr8tsr90=,tag:1bYmThm+xZ1cGMDku/wq8g==,type:str]
    LDAP_BIND_DN: ENC[AES256_GCM,data:GFfVl6sQ70zhVP8nymMTfKxN5WBcsz4VpYXY7+znfe3keJ76ONzVtwd/,iv:9n2h3NTYsPjGsY6f4QPT/545iM876vut5O2huv60sxo=,tag:uG1dAx73NgfTPq66pSmKVg==,type:str]
    LDAP_SEARCH_BASE: ENC[AES256_GCM,data:0eLYbucE+DDbQkoSGoZTGQ7QSto9QYB0QkU8DiwTDio=,iv:b9Dg6kcrX6Sa01OZ/IUA8eHvy2W/JJZGuVTC7f7tE/A=,tag:F1VseuNt1bXKUBcc7/Nujw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdHBZMFg2d2tnVDBxZEgv
            VHBXdW1BZjgvR3VaRVdZc0tKYTBGYklhVlVVClg5ekFaL2VWRkxhcUkrWG5nNDVy
            SjdNUzl0eUZJWnZmSHhzblFkeG5IZjgKLS0tIHVuckI5cGs4Vmw4cVJhbExCb1h1
            eUhjVWM0akFpb0ZJbmk3aDROa0p1dFEKJugL0GI064LGmZkP/nTn9aOwdBmG94Jj
            VyBY7MJ4IWUWuLJrBkBJPooyE/bb0HM03gi7p7LNNpipaqb5yiu3YA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-06T23:19:39Z"
    mac: ENC[AES256_GCM,data:CLPcSCiijnWPQIVbYoZSTZD+AuVE+/+Fj774+kKo5RZgUBXns88givP4MZVPM375JACab8BQ6XyijriKCvKetlHZvQWtua5IRUOi9BbS2EYa+RBE+GrjfRnGi+UpMkrqudWOFLQiwjZ4srlry56SotH6LV93HTtvwRkDJXg+eTc=,iv:g02T4+2Bvi4GS8l6NNua182LnJFsMlALwWR0sQ2RkZY=,tag:t2VKR8wbnKpOTE1zXOtsSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.8.1
