---
theme: dark
server:
  address: tcp://0.0.0.0:9091
  disable_healthcheck: true
log:
  level: debug
totp:
  disable: false
webauthn:
  disable: true
authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 1m
  ldap:
    implementation: custom
    address: ldap://lldap.auth-system.svc.cluster.local:389
    timeout: 5s
    start_tls: false
    additional_users_dn: ou=people
    users_filter: "(&({username_attribute}={input})(objectClass=person))"
    additional_groups_dn: ou=groups
    groups_filter: "(member={dn})"
    group_search_mode: filter
    attributes:
      username: uid
      display_name: displayName
      mail: mail
      group_name: cn
      member_of: memberOf
access_control:
  default_policy: deny
  networks:
    - name: internal
      networks:
        - 10.0.0.0/8
  rules:
    - domain: "*.${SECRET_DOMAIN}"
      networks:
        - internal
      policy: bypass
    - domain: "*.${SECRET_DOMAIN}"
      policy: two_factor
session:
  name: authelia_session
  expiration: 1h
  inactivity: 15m
  remember_me: 1M
  cookies:
    - domain: ${SECRET_DOMAIN}
      authelia_url: https://auth.${SECRET_DOMAIN}
      default_redirection_url: https://${SECRET_DOMAIN}
regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m
notifier:
  disable_startup_check: false
  smtp:
    address: submission://mail.${SECRET_DOMAIN}:587
    username: admin@${SECRET_DOMAIN}
    sender: Authelia Admin <admin@${SECRET_DOMAIN}>
