---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app ingress-nginx
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: networking-system
  releaseName: *app
  chart:
    spec:
      chart: *app
      version: 4.10.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 10m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    tcp:
      "25": "mail-system/docker-mailserver:25"
      "143": "mail-system/docker-mailserver:143"
      "465": "mail-system/docker-mailserver:465"
      "587": "mail-system/docker-mailserver:587"
      "993": "mail-system/docker-mailserver:993"
      "995": "mail-system/docker-mailserver:995"
      "389": "auth-system/lldap:389"
      "5432": "postgres-operator/pgo-cluster-ha:5432"
    controller:
      kind: DaemonSet
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      hostPort:
        enabled: true
        http: 80
        https: 443
      service:
        enabled: false
      admissionWebhooks:
        enabled: false
      metrics:
        enabled: true
      ingressClassResource:
        default: true
      config:
        use-forwarded-headers: "true"
        use-regex: "true"
        use-geoip: "true"
        use-real-ip: "true"
        use-ssl-passthrough: "true"
        use-status: "true"
        use-secure-backends: "true"
        use-snippets: "true"
        use-annotations: "true"
