# yaml-language-server: $schema=https://raw.githubusercontent.com/marcolongol/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1beta1.json
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: speedtest-tracker-secret
  namespace: speedtest-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: speedtest-tracker-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        APP_KEY: |-
          {{ .APP_KEY }}
  dataFrom:
    - extract:
        key: SPEEDTEST
