apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql
  namespace: postgres-operator
data:
  init.sql: |
    \c postgres
    GRANT ALL PRIVILEGES ON DATABASE authelia TO authelia;
    GRANT ALL PRIVILEGES ON DATABASE awx TO awx;
    \c authelia
    GRANT ALL PRIVILEGES ON SCHEMA public TO authelia;
    \c awx
    GRANT ALL PRIVILEGES ON SCHEMA public TO awx;
