apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql
  namespace: postgres-operator
data:
  init.sql: |
    \c postgres
    GRANT ALL PRIVILEGES ON DATABASE authelia TO authelia;
    GRANT ALL PRIVILEGES ON DATABASE awx TO awx;
    GRANT ALL PRIVILEGES ON DATABASE fireflyiii TO fireflyiii;
    GRANT ALL PRIVILEGES ON DATABASE marcolongodb_dev TO marcolongodb;
    GRANT ALL PRIVILEGES ON DATABASE marcolongodb_test TO marcolongodb;
    GRANT ALL PRIVILEGES ON DATABASE marcolongodb TO marcolongodb;
    GRANT ALL PRIVILEGES ON DATABASE unleash TO unleash;
    \c authelia
    GRANT ALL PRIVILEGES ON SCHEMA public TO authelia;
    \c awx
    GRANT ALL PRIVILEGES ON SCHEMA public TO awx;
    \c fireflyiii
    GRANT ALL PRIVILEGES ON SCHEMA public TO fireflyiii;
    \c marcolongodb_dev
    GRANT ALL PRIVILEGES ON SCHEMA public TO marcolongodb;
    \c marcolongodb_test
    GRANT ALL PRIVILEGES ON SCHEMA public TO marcolongodb;
    \c marcolongodb
    GRANT ALL PRIVILEGES ON SCHEMA public TO marcolongodb;
    \c unleash
    GRANT ALL PRIVILEGES ON SCHEMA public TO unleash;
