apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql
  namespace: postgres-operator
data:
  init.sql: |
    \c postgres
    GRANT ALL PRIVILEGES ON DATABASE authelia TO authelia;
    GRANT ALL PRIVILEGES ON DATABASE awx TO awx;
    GRANT ALL PRIVILEGES ON DATABASE dev_marcolongocloud TO marcolongocloud;
    GRANT ALL PRIVILEGES ON DATABASE test_marcolongocloud TO marcolongocloud;
    GRANT ALL PRIVILEGES ON DATABASE prod_marcolongocloud TO marcolongocloud;
    \c authelia
    GRANT ALL PRIVILEGES ON SCHEMA public TO authelia;
    \c awx
    GRANT ALL PRIVILEGES ON SCHEMA public TO awx;
    \c dev_marcolongocloud
    GRANT ALL PRIVILEGES ON SCHEMA public TO marcolongocloud;
    \c test_marcolongocloud
    GRANT ALL PRIVILEGES ON SCHEMA public TO marcolongocloud;
    \c prod_marcolongocloud
