---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mayastor
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: storage-system
  releaseName: *app
  chart:
    spec:
      chart: *app
      version: 2.6.1
      sourceRef:
        kind: HelmRepository
        name: mayastor
        namespace: flux-system
      interval: 10m
  install:
    timeout: 30m
    replace: true
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 5
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace
  rollback:
    recreate: true
    force: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  maxHistory: 3
  values:
    jaeger:
      enabled: false
    loki-stack:
      enabled: false
    obs:
      callhome:
        enabled: false
    storageClass:
      enabled: false
    io_engine:
      cpuCount: 1
