---
# yaml-language-server: $schema=https://raw.githubusercontent.com/marcolongol/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-secret
  namespace: storage-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: minio-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MINIO_ROOT_USER: |-
          {{ .MINIO_ROOT_USER }}
        MINIO_ROOT_PASSWORD: |-
          {{ .MINIO_ROOT_PASSWORD }}
        MINIO_IDENTITY_OPENID_CLIENT_ID: |-
          {{ .MINIO_OAUTH_CLIENT_ID }}
        MINIO_IDENTITY_OPENID_CLIENT_SECRET: |-
          {{ .MINIO_OAUTH_CLIENT_SECRET }}
  dataFrom:
    - extract:
        key: MINIO
