---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-admin-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-admin-binding
subjects:
  - kind: Group
    name: oidc:k8s_admin
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: k8s-admin-role
  apiGroup: rbac.authorization.k8s.io
