---
# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus
  namespace: networking-system
  labels:
    app.kubernetes.io/name: nexus
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
    nginx.ingress.kubernetes.io/whitelist-source-range: ${CONFIG_NGINX_WHITELIST}
spec:
  ingressClassName: nginx
  rules:
    - host: &host nexus.${SECRET_DOMAIN_0}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portainer
                port:
                  number: 443
  tls:
    - hosts:
        - *host
      secretName: ${SECRET_DOMAIN_0}-prod
