---
# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opnsense
  namespace: networking-system
  labels:
    app.kubernetes.io/name: opnsense
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8
spec:
  ingressClassName: nginx
  rules:
    - host: &host opnsense.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opnsense
                port:
                  number: 443
  tls:
    - hosts:
        - *host
      secretName: ingress-nginx-tls
