---
clusterName: talos-cluster
talosVersion: 1.9.1
kubernetesVersion: v1.31.0
endpoint: https://10.0.0.200:6443
allowSchedulingOnMasters: true
cniConfig:
  name: none

patches:
  - |-
    cluster:
      proxy:
        disabled: true
  - |-
    machine:
      kubelet:
        extraConfig:
          serverTLSBootstrap: true

nodes:
  - hostname: talos01
    ipAddress: "10.0.0.3"
    controlPlane: true
    installDisk: /dev/vda

  - hostname: talos02
    ipAddress: "10.0.0.4"
    controlPlane: true
    installDisk: /dev/vda

  - hostname: talos03
    ipAddress: "10.0.0.5"
    controlPlane: true
    installDisk: /dev/vda

  - hostname: talos04
    ipAddress: "10.0.0.6"
    controlPlane: false
    installDisk: /dev/vda

  - hostname: talos05
    ipAddress: "10.0.0.7"
    controlPlane: false
    installDisk: /dev/vda

  - hostname: talos06
    ipAddress: "10.0.0.8"
    controlPlane: false
    installDisk: /dev/vda

controlPlane:
  networkInterfaces:
    - interface: eth0
      dhcp: true
      routes:
        - network: 0.0.0.0/0
          gateway: 10.0.0.1
      vip:
        ip: 10.0.0.200
  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=0
      systemExtensions:
        officialExtensions:
          - siderolabs/qemu-guest-agent
  patches:
    - |-
      - op: add
        path: /machine/sysctls
        value:
          vm.nr_hugepages: 1024
    - |-
      - op: add
        path: /cluster/apiServer/extraArgs
        value:
          oidc-issuer-url: ${KUBERNETES_OIDC_ISSUER_URL}
          oidc-client-id: ${KUBERNETES_OIDC_CLIENT_ID}
          oidc-username-claim: email
          oidc-username-prefix: "oidc:"
          oidc-groups-claim: groups
          oidc-groups-prefix: "oidc:"
  nodeLabels:
    openebs.io/engine: mayastor

worker:
  networkInterfaces:
    - interface: eth0
      dhcp: true
      routes:
        - network: 0.0.0.0/0
          gateway: 10.0.0.1
  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=0
      systemExtensions:
        officialExtensions:
          - siderolabs/qemu-guest-agent
