---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: docker-mailserver
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: mail-system
  releaseName: docker-mailserver
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      hostname: "mail.${SECRET_DOMAIN}"
    controllers:
      docker-mailserver:
        containers:
          autodiscover:
            image:
              repository: monogramm/autodiscover-email-settings
              tag: latest
            env:
              OVERRIDE_HOSTNAME: autodiscover.${SECRET_DOMAIN}
              COMPANY_NAME: "${SECRET_DOMAIN} Mail"
              SUPPORT_URL: "https://autodiscover.${SECRET_DOMAIN}"
              IMAP_HOST: mail.${SECRET_DOMAIN}
              IMAP_PORT: "143"
              IMAP_SOCKET: "SSL"
              SMTP_HOST: mail.${SECRET_DOMAIN}
              SMTP_PORT: "587"
              SMTP_SOCKET: "STARTTLS"
          roundcubemail:
            image:
              repository: roundcube/roundcubemail
              tag: 1.6.6-apache
            env:
              OVERRIDE_HOSTNAME: webmail.${SECRET_DOMAIN}
              ROUNDCUBE_DB_TYPE: sqlite
              ROUNDCUBEMAIL_SKIN: elastic
              ROUNDCUBEMAIL_DEFAULT_HOST: tls://mail.${SECRET_DOMAIN}
              ROUNDCUBEMAIL_DEFAULT_PORT: 143
              ROUNDCUBEMAIL_SMTP_SERVER: tls://mail.${SECRET_DOMAIN}
              ROUNDCUBEMAIL_SMTP_PORT: 587
          docker-mailserver:
            image:
              repository: ghcr.io/docker-mailserver/docker-mailserver
              tag: 13.3.1
            env:
              - name: LOG_LEVEL
                value: "debug"
              - name: SUPERVISOR_LOGLEVEL
                value: "debug"
              - name: OVERRIDE_HOSTNAME
                value: mail.${SECRET_DOMAIN}
              - name: SPAMASSASSIN_SPAM_TO_INBOX
                value: 1
              - name: ENABLE_FAIL2BAN
                value: 0
              - name: ENABLE_AMAVIS
                value: 0
              - name: SPOOF_PROTECTION
                value: 0
              - name: ENABLE_OPENDKIM
                value: 0
              - name: ENABLE_OPENDMARC
                value: 1
              - name: SSL_TYPE
                value: manual
              - name: SSL_CERT_PATH
                value: /tmp/dms/custom-certs/public.crt
              - name: SSL_KEY_PATH
                value: /tmp/dms/custom-certs/private.key
              - name: ACCOUNT_PROVISIONER
                value: LDAP
              - name: LDAP_SERVER_HOST
                value: ldap://lldap.auth-system.svc.cluster.local
              - name: LDAP_SEARCH_BASE
                valueFrom:
                  secretKeyRef:
                    name: lldap-secret
                    key: LDAP_SEARCH_BASE
              - name: LDAP_BIND_DN
                valueFrom:
                  secretKeyRef:
                    name: lldap-secret
                    key: LDAP_BIND_DN
              - name: LDAP_BIND_PW
                valueFrom:
                  secretKeyRef:
                    name: lldap-secret
                    key: LLDAP_LDAP_USER_PASS
              - name: LDAP_QUERY_FILTER
                value: "(&(objectClass=inetOrgPerson)(|(uid=%u)(mail=%u)))"
              - name: LDAP_QUERY_FILTER_GROUP
                value: "(&(objectClass=groupOfUniqueNames)(uid=%s))"
              - name: LDAP_QUERY_FILTER_ALIAS
                value: "(&(objectClass=inetOrgPerson)(|(uid=%u)(mail=%u)))"
              - name: LDAP_QUERY_FILTER_DOMAIN
                value: "(mail=*@%s)"
              - name: DOVECOT_AUTH_BIND
                value: yes
              - name: DOVECOT_USER_FILTER
                value: "(&(objectClass=inetOrgPerson)(|(uid=%u)(mail=%u)))"
              - name: DOVECOT_USER_ATTRS
                value: "=uid=5000,=gid=5000,=home=/var/mail/%Ln,=mail=maildir:~/Maildir"
              - name: POSTMASTER_ADDRESS
                value: postmaster@${SECRET_DOMAIN}
    service:
      main:
        controller: docker-mailserver
        ports:
          http:
            enabled: true
            protocol: TCP
            port: 80
            targetPort: 80
          https:
            enabled: true
            protocol: TCP
            port: 443
            targetPort: 8000
          smtp:
            enabled: true
            primary: true
            protocol: TCP
            port: 25
            targetPort: 25
          submission:
            enabled: true
            protocol: TCP
            port: 587
            targetPort: 587
          imap:
            enabled: true
            protocol: TCP
            port: 143
            targetPort: 143
          imaps:
            enabled: true
            protocol: TCP
            port: 993
            targetPort: 993
          pop3:
            enabled: true
            protocol: TCP
            port: 465
            targetPort: 465
          pop3s:
            enabled: true
            protocol: TCP
            port: 995
            targetPort: 995
    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: &host1 autoconfig.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: https
          - host: &host2 autodiscover.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: https
          - host: &host3 webmail.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host1
              - *host2
              - *host3
            secretName: ingress-nginx-tls
    persistence:
      tls:
        enabled: true
        type: secret
        name: ingress-nginx-tls
        globalMounts:
          - path: /tmp/dms/custom-certs/private.key
            subPath: tls.key
            readOnly: true
          - path: /tmp/dms/custom-certs/public.crt
            subPath: tls.crt
            readOnly: true
