---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: docker-mailserver
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: mail-system
  releaseName: docker-mailserver
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      hostname: "mail.${SECRET_DOMAIN_0}"
    controllers:
      docker-mailserver:
        containers:
          autodiscover:
            image:
              repository: monogramm/autodiscover-email-settings
              tag: latest
            env:
              OVERRIDE_HOSTNAME: autodiscover.${SECRET_DOMAIN_0}
              COMPANY_NAME: "${SECRET_DOMAIN_0} Mail"
              SUPPORT_URL: "https://autodiscover.${SECRET_DOMAIN_0}"
              IMAP_HOST: mail.${SECRET_DOMAIN_0}
              IMAP_PORT: "143"
              IMAP_SOCKET: "SSL"
              SMTP_HOST: mail.${SECRET_DOMAIN_0}
              SMTP_PORT: "587"
              SMTP_SOCKET: "STARTTLS"
          roundcubemail:
            image:
              repository: roundcube/roundcubemail
              tag: 1.6.9-apache
            env:
              OVERRIDE_HOSTNAME: webmail.${SECRET_DOMAIN_0}
              ROUNDCUBE_DB_TYPE: sqlite
              ROUNDCUBEMAIL_SKIN: elastic
              ROUNDCUBEMAIL_DEFAULT_HOST: tls://mail.${SECRET_DOMAIN_0}
              ROUNDCUBEMAIL_DEFAULT_PORT: 143
              ROUNDCUBEMAIL_SMTP_SERVER: tls://mail.${SECRET_DOMAIN_0}
              ROUNDCUBEMAIL_SMTP_PORT: 587
          docker-mailserver:
            image:
              repository: ghcr.io/docker-mailserver/docker-mailserver
              tag: 14.0.0
            env:
              ACCOUNT_PROVISIONER: LDAP
              DOVECOT_AUTH_BIND: yes
              DOVECOT_USER_ATTRS: "=uid=5000,=gid=5000,=home=/var/mail/%Ln,=mail=maildir:~/Maildir"
              DOVECOT_USER_FILTER: "(&(objectClass=inetOrgPerson)(|(uid=%u)(mail=%u)))"
              ENABLE_AMAVIS: 0
              ENABLE_FAIL2BAN: 1
              ENABLE_OPENDKIM: 1
              ENABLE_OPENDMARC: 1
              LDAP_BIND_DN:
                valueFrom:
                  secretKeyRef:
                    name: lldap-secret
                    key: LDAP_BIND_DN
              LDAP_BIND_PW:
                valueFrom:
                  secretKeyRef:
                    name: lldap-secret
                    key: LLDAP_LDAP_USER_PASS
              LDAP_SEARCH_BASE:
                valueFrom:
                  secretKeyRef:
                    name: lldap-secret
                    key: LDAP_SEARCH_BASE
              LDAP_QUERY_FILTER_ALIAS: "(&(objectClass=inetOrgPerson)(|(uid=%u)(mail=%u)))"
              LDAP_QUERY_FILTER_DOMAIN: "(mail=*@%s)"
              LDAP_QUERY_FILTER_GROUP: "(&(objectClass=webmail_user)(uid=%s))"
              LDAP_QUERY_FILTER: "(&(objectClass=inetOrgPerson)(|(uid=%u)(mail=%u)))"
              LDAP_SERVER_HOST: ldap://lldap.auth-system.svc.cluster.local
              LOG_LEVEL: debug
              OVERRIDE_HOSTNAME: mail.${SECRET_DOMAIN_0}
              POSTMASTER_ADDRESS: postmaster@${SECRET_DOMAIN_0}
              SPAMASSASSIN_SPAM_TO_INBOX: 1
              SPOOF_PROTECTION: 0
              SSL_CERT_PATH: /tmp/dms/custom-certs/public.crt
              SSL_KEY_PATH: /tmp/dms/custom-certs/private.key
              SSL_TYPE: manual
              SUPERVISOR_LOGLEVEL: debug
    service:
      main:
        controller: docker-mailserver
        ports:
          http:
            enabled: true
            protocol: TCP
            port: 80
            targetPort: 80
          https:
            enabled: true
            protocol: TCP
            port: 443
            targetPort: 8000
          smtp:
            enabled: true
            primary: true
            protocol: TCP
            port: 25
            targetPort: 25
          submission:
            enabled: true
            protocol: TCP
            port: 587
            targetPort: 587
          imap:
            enabled: true
            protocol: TCP
            port: 143
            targetPort: 143
          imaps:
            enabled: true
            protocol: TCP
            port: 993
            targetPort: 993
          pop3:
            enabled: true
            protocol: TCP
            port: 465
            targetPort: 465
          pop3s:
            enabled: true
            protocol: TCP
            port: 995
            targetPort: 995
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/auth-method: "GET"
          nginx.ingress.kubernetes.io/auth-url: "http://authelia.auth-system.svc.cluster.local:9091/api/verify"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN_0}?rm=$request_method"
          nginx.ingress.kubernetes.io/auth-response-headers: "Remote-User,Remote-Name,Remote-Groups,Remote-Email"
        hosts:
          - host: &host1 autoconfig.${SECRET_DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: https
          - host: &host2 autodiscover.${SECRET_DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: https
          - host: &host3 webmail.${SECRET_DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host1
              - *host2
              - *host3
            secretName: ${SECRET_DOMAIN_0}-prod
    persistence:
      tls:
        enabled: true
        type: secret
        name: ${SECRET_DOMAIN_0}-prod
        globalMounts:
          - path: /tmp/dms/custom-certs/private.key
            subPath: tls.key
            readOnly: true
          - path: /tmp/dms/custom-certs/public.crt
            subPath: tls.crt
            readOnly: true
      spf-config:
        enabled: true
        type: configMap
        name: spf-config
        globalMounts:
          - path: /etc/postfix-policyd-spf-python/policyd-spf.conf
            subPath: policyd-spf.conf
            readOnly: true
      mail-data:
        enabled: true
        storageClass: mayastor-nvmf
        accessMode: ReadWriteOnce
        size: 2Gi
        globalMounts:
          - path: /var/mail
        retain: false
      mail-state:
        enabled: true
        storageClass: mayastor-nvmf
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /var/mail-state
        retain: false
      mail-logs:
        enabled: true
        storageClass: mayastor-nvmf
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /var/log/mail
        retain: false
      mail-config:
        enabled: true
        storageClass: mayastor-nvmf
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /tmp/docker-mailserver
        retain: false
