# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app actual
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: finance-system
  releaseName: *app
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      actual:
        containers:
          app:
            image:
              repository: ghcr.io/actualbudget/actual-server
              tag: 25.1.0
            env:
              ACTUAL_PORT: &httpPort 5006
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *httpPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            resources:
              requests:
                cpu: 12m
                memory: 128M
              limits:
                memory: 512M
    service:
      app:
        controller: actual
        ports:
          http:
            port: *httpPort
    ingress:
      app:
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: ${CONFIG_NGINX_WHITELIST}
          nginx.ingress.kubernetes.io/auth-method: "GET"
          nginx.ingress.kubernetes.io/auth-url: "http://authelia.auth-system.svc.cluster.local:9091/api/verify"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN_0}?rm=$request_method"
          nginx.ingress.kubernetes.io/auth-response-headers: "Remote-User,Remote-Name,Remote-Groups,Remote-Email"
        hosts:
          - host: &host money.${SECRET_DOMAIN_0}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: ${SECRET_DOMAIN_0}-prod
    persistence:
      data:
        storageClass: smb
        accessMode: ReadWriteOnce
        size: 5Gi
        globalMounts:
          - path: /data
