---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app reloader
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: reloader-system
  releaseName: *app
  chart:
    spec:
      chart: reloader
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    reloader:
      readOnlyRootFileSystem: true
