---
# yaml-language-server: $schema=https://raw.githubusercontent.com/marcolongol/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secret
  namespace: auth-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: oauth2-proxy-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client-id: |-
          {{ .KUBERNETES_OIDC_CLIENT_ID }}
        client-secret: |-
          {{ .KUBERNETES_OIDC_CLIENT_SECRET }}
        cookie-secret: |-
          {{ .OAUTH2_PROXY_COOKIE_SECRET }}
  dataFrom:
    - extract:
        key: OAUTH2_PROXY
    - extract:
        key: KUBERNETES
