---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cilium/kustomization-fluxCRD.yaml
  - ./kubelet-csr-approver/kustomization-fluxCRD.yaml
  - ./reflector/kustomization-fluxCRD.yaml
