---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
  namespace: flux-system
data:
  CONFIG_PROXMOX_IP_ADDRESS: 10.10.10.0
  CONFIG_OPNSENSE_IP_ADDRESS: 10.0.0.1
  CONFIG_DOCKER_SERVER_IP_ADDRESS: 10.0.0.2
