# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret-vars
    namespace: flux-system
type: Opaque
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:XAh9g81VU0e1GEuPCwS8RQ==,iv:Is+bibwwOyocdI74OYkOrJr98HToQnyF68/cER3jKWk=,tag:dUj10XbMul3WpCkk98jSxA==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:UGSYyvfT6oReXZgTjwOZlVe3UXB/gw==,iv:ByjLe+em+2UWt1OLhM4vy1KabeZadVlNmgdAWKpXK18=,tag:PYwQdQJdoSnrQPSD98irrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19r6wen3fypsw5ykk0dj2e2hc0tyw2zlux6mw33c57pfg5jd9mg9sgjp3za
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRENlSFZWRHM5UE1qR2Y5
            N2Z6Qk1nMytQTW9NbkpCdG9TSTFQYWJyYmhnCmhqbGNObDZxVUUvWUdwNmVlVWs5
            RnlzODJSRUdWN2ZRSUxDTE1QTCtVYncKLS0tIHNxTkoyUlhHRGJJSDh4MWRmbHor
            aitoVnBuWVVqOFYrcjl2bld3MjlFSlkKZ/ujcO6m6CuwY8bijj4C7xF0Q3aLQj5y
            Aw12f8cnkYccj41QsM1kO211cNDoDPPW/i3M0pWscm3brMBTs8NA3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-24T01:43:23Z"
    mac: ENC[AES256_GCM,data:H/AoMxH0LN9cunEwVlZP0GaR38YOBgmudDC26NdOHRCcJ0OxJbLwnvAfYKQEmIJkHngZ98bb0HjhISz9Ac8mAT8cROyh6p+IBGiaLqMpOsjA/X2o9vzD91r0nZKjCGxnnPBFZ8ErgTLQfVr0f/r8gGC9kClpHHxpOzzstSUA0VQ=,iv:ZMGC8gr7GAMbT/vHJGOmRoTfeVyI9Lpv7ebmt/5TzJ8=,tag:8gk7TVcQ57WeeLJdh3o4KQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.8.1
