---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server-base
  namespace: flux-system
spec:
  path: ./kubernetes/cluster/apps/monitoring-system/metrics-server/base
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  prune: true
  wait: true
