# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly-iii
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: finance-system
  releaseName: firefly-iii
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      hostname: "money.${SECRET_DOMAIN_0}"
    controllers:
      firefly-iii:
        containers:
          main:
            image:
              repository: fireflyiii/core
              tag: version-6.1.19
            resources:
              requests:
                cpu: 15m
                memory: 164Mi
              limits:
                memory: 175Mi
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            envFrom:
              - secretRef:
                  name: firefly-iii-secret
            env:
              DB_CONNECTION: pgsql
              DB_HOST:
                valueFrom:
                  secretKeyRef:
                    name: pgo-cluster-pguser-fireflyiii
                    key: host
              DB_PORT:
                valueFrom:
                  secretKeyRef:
                    name: pgo-cluster-pguser-fireflyiii
                    key: port
              DB_DATABASE:
                valueFrom:
                  secretKeyRef:
                    name: pgo-cluster-pguser-fireflyiii
                    key: dbname
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: pgo-cluster-pguser-fireflyiii
                    key: user
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: pgo-cluster-pguser-fireflyiii
                    key: password
        initContainers:
          wait-database:
            image:
              repository: alpine
              tag: 3.20.3
              pullPolicy: IfNotPresent
            command:
              - sh
            args:
              - -c
              - >-
                until nc -w 1 -v $MYSQL_HOST:3306 || nc -w 1 -v $POSTGRES_HOST:5432;
                do echo "Waiting for database";
                done
            env:
              - name: POSTGRES_HOST
                valueFrom:
                  secretKeyRef:
                    name: pgo-cluster-pguser-fireflyiii
                    key: host
    service:
      main:
        controller: firefly-iii
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: ${CONFIG_NGINX_WHITELIST}
          nginx.ingress.kubernetes.io/auth-method: "GET"
          nginx.ingress.kubernetes.io/auth-url: "http://authelia.auth-system.svc.cluster.local:9091/api/verify"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN_0}?rm=$request_method"
          nginx.ingress.kubernetes.io/auth-response-headers: "Remote-User,Remote-Name,Remote-Groups,Remote-Email"
        hosts:
          - host: &host money.${SECRET_DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: ingress-nginx-prod
    persistence:
      data:
        enabled: true
        storageClass: mayastor-nvmf
        accessMode: ReadWriteOnce
        size: 2Gi
        advancedMounts:
          firefly-iii:
            main:
              - path: /var/www/html/storage/upload
