name: Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}

env:
  packages_to_install: kubeconform yq kustomize

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Install Scoop
        uses: MinoruSekine/setup-scoop@v4
        with:
          install_scoop: "true"
          buckets: "extras"
          scoop_update: "true"
          update_path: "true"

      - name: Install packages
        run: |
          scoop install ${{ env.packages_to_install }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        shell: pwsh
        run: |
          Invoke-Pester ./tests -Output Detailed
